apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pedidos-ms-postgres
  namespace: pedidos-ms
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
