apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-ms-configmap
  namespace: totem
data:
  POSTGRES_USER: pedidos-ms
  POSTGRES_DB: pedidos-ms
  PGDATA: /application/postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: "postgresql://pedidos-ms:pedidos-ms@pedidos-ms-postgres:5432/pedidos-ms"
  API_GATEWAY_LAMBDA_COGNITO: "https://1r8kzbgt4h.execute-api.us-east-1.amazonaws.com/Prod"
  PORT: "3000"
  PAYMENT_API_URL: "http://payment-ms"
  PRODUCT_API_URL: "http://produtos-ms"
