apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: pedidos-ms
    namespace: totem
spec:
    scaleTargetRef:
        kind: Deployment
        name: pedidos-ms
        apiVersion: apps/v1
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 30