apiVersion: v1
kind: Service
metadata:
  labels:
    run: pedidos-ms
  name: pedidos-ms
  namespace: pedidos-ms
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32222
  selector:
    app: pedidos-ms

---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-ms
  namespace: pedidos-ms
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: pedidos-ms
